# Generated by Boost 1.87.0

if(TARGET Boost::headers)
  return()
endif()

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_headers ${boost_headers_VERSION} at ${boost_headers_DIR}")
endif()

mark_as_advanced(boost_headers_DIR)

# Compute the include and library directories relative to this file.

get_filename_component(_BOOST_REAL_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" REALPATH)

# If the computed and the original directories are symlink-equivalent, use original
if(EXISTS "/nix/store/3qm4f18mq6ni4dml1w1c6ga7jw6khjyq-boost-1.87.0/lib/cmake")
  get_filename_component(_BOOST_CMAKEDIR_ORIGINAL "/nix/store/3qm4f18mq6ni4dml1w1c6ga7jw6khjyq-boost-1.87.0/lib/cmake" REALPATH)
  if(_BOOST_CMAKEDIR STREQUAL _BOOST_CMAKEDIR_ORIGINAL)
    set(_BOOST_CMAKEDIR "/nix/store/3qm4f18mq6ni4dml1w1c6ga7jw6khjyq-boost-1.87.0/lib/cmake")
  endif()
  unset(_BOOST_CMAKEDIR_ORIGINAL)
endif()

# Assume that the installer actually did know where the libs were to be installed
get_filename_component(_BOOST_CMAKEDIR "/nix/store/3qm4f18mq6ni4dml1w1c6ga7jw6khjyq-boost-1.87.0/lib/cmake" REALPATH)
get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../../wmrsz37zxjpz6qj146dli1q9xspbsh22-boost-1.87.0-dev/include/" ABSOLUTE)

add_library(Boost::headers INTERFACE IMPORTED)

set_target_properties(Boost::headers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
)

unset(_BOOST_INCLUDEDIR)
unset(_BOOST_CMAKEDIR)
