# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml
on: [push, pull_request]
name: CI
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
        env:
          RUST_BACKTRACE: 1
      - name: Compile WASM contract (cw4626-base)
        uses: actions-rs/cargo@v1
        with:
          command: wasm
          args: --locked -p cw4626-base
        env:
          RUSTFLAGS: "-C link-arg=-s"
      - name: Clean environment
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Compile WASM contract (cw4626-escher)
        uses: actions-rs/cargo@v1
        with:
          command: wasm
          args: --locked -p cw4626-escher
        env:
          RUSTFLAGS: "-C link-arg=-s"
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Generate Schema (cw4626-base)
        uses: actions-rs/cargo@v1
        with:
          command: schema
          args: --locked -p cw4626-base
      - name: Generate Schema (cw4626-escher)
        uses: actions-rs/cargo@v1
        with:
          command: schema
          args: --locked -p cw4626-escher
      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
